/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useState, useEffect, useMemo } from "react";

const STORAGE_KEY = "koupreng.admin.lang";

export const ADMIN_DICTIONARY = {
  km: {
    brandName: "គូព្រេង KOUPRENG",
    brandSub: "ប្រព័ន្ធគ្រប់គ្រងគូព្រេង",
    nav: {
      overview: "ទិដ្ឋភាពទូទៅ",
      dashboard: "ផ្ទាំងគ្រប់គ្រង",
      management: "ការគ្រប់គ្រងទូទៅ",
      users: "អ្នកប្រើប្រាស់",
      catalog: "គំរូ & កញ្ចប់សេវា",
      templates: "គំរូធៀបការ",
      packages: "កញ្ចប់សេវាកម្ម",
      finance: "ហិរញ្ញវត្ថុ & របាយការណ៍",
      payments: "ការទូទាត់ (KHQR)",
      reports: "របាយការណ៍",
      system: "ប្រព័ន្ធ & សុវត្ថិភាព",
      notifications: "ការជូនដំណឹង",
      systemLogs: "កំណត់ហេតុប្រព័ន្ធ",
    },
    topMenu: {
      notifications: "ការជូនដំណឹង",
      themeLight: "ប្ដូរទៅ Light Mode",
      themeDark: "ប្ដូរទៅ Dark Mode",
      language: "ភាសា",
      superAdmin: "SUPER ADMIN",
      account: "គណនី",
      profile: "ប្រវត្តិរូប",
      signOut: "ចាកចេញពីប្រព័ន្ធ",
      allUsers: "បញ្ជីអ្នកប្រើប្រាស់ទាំងអស់",
      searchPlaceholder: "ស្វែងរកទិន្នន័យ (ឈ្មោះ, អ៊ីមែល, លេខកូដ)...",
    },
    pageTitles: {
      "/dashboard": "ផ្ទាំងគ្រប់គ្រងទូទៅ",
      "/users": "គ្រប់គ្រងអ្នកប្រើប្រាស់",
      "/templates": "គ្រប់គ្រងគំរូធៀបការ",
      "/packages": "គ្រប់គ្រងកញ្ចប់សេវាកម្ម",
      "/payments": "របាយការណ៍ការទូទាត់ (KHQR)",
      "/notifications": "គ្រប់គ្រងការជូនដំណឹង",
      "/system-logs": "កំណត់ហេតុប្រព័ន្ធ",
      "/reports": "របាយការណ៍សង្ខេប & Analytics",
      fallback: "ផ្ទាំងរដ្ឋបាលគូព្រេង",
    },
    common: {
      search: "ស្វែងរក...",
      filter: "ចម្រោះ",
      all: "ទាំងអស់",
      active: "សកម្ម",
      inactive: "អសកម្ម",
      published: "ផ្សាយផ្ទាល់",
      draft: "ព្រាង",
      create: "បង្កើតថ្មី",
      edit: "កែប្រែ",
      delete: "លុប",
      save: "រក្សាទុក",
      cancel: "បោះបង់",
      loading: "កំពុងដំណើរការ...",
      noData: "គ្មានទិន្នន័យទេ",
      actions: "សកម្មភាព",
      status: "ស្ថានភាព",
      date: "កាលបរិច្ឆេទ",
      close: "បិទ",
      refresh: "ផ្ទុកឡើងវិញ",
      retry: "ព្យាយាមម្តងទៀត",
      viewAll: "មើលទាំងអស់",
      collapseMenu: "បង្រួម Menu",
      expandMenu: "ពង្រីក Menu",
    },
    dashboard: {
      eyebrow: "ទិដ្ឋភាពទូទៅនៃប្រព័ន្ធ",
      title: "ផ្ទាំងគ្រប់គ្រង",
      subtitle: "ការវិភាគទិន្នន័យទូទៅ សកម្មភាពអ្នកប្រើប្រាស់ និងសុខភាពប្រព័ន្ធ",
      reload: "ផ្ទុកឡើងវិញ",
      loading: "កំពុងទាញយកទិន្នន័យផ្ទាំងគ្រប់គ្រង...",
      error: "មិនអាចទាញយកទិន្នន័យ Dashboard បានទេ",
      totalUsers: "អ្នកប្រើសរុប",
      activeAccounts: "គណនី Active",
      totalTemplates: "គំរូធៀបការ",
      premiumTemplates: "Premium",
      totalInvitations: "ធៀបការសរុប",
      publishedInvitations: "បានផ្សាយ",
      totalGuests: "ភ្ញៀវសរុប (Guests)",
      allGuestsNote: "ភ្ញៀវក្នុងធៀបការទាំងអស់",
      totalPayments: "ការទូទាត់សរុប",
      failedPayments: "បរាជ័យ",
      totalRevenue: "ចំណូលសរុប",
      normalOperation: "ដំណើរការធម្មតា",
      rsvpConversion: "RSVP Conversion",
      rsvpRateNote: "អត្រាឆ្លើយតបធៀបនឹងចំនួនភ្ញៀវ",
      checkInRate: "Check-in Rate",
      checkedInGuests: "ភ្ញៀវបាន Check-in",
      telegramDelivery: "Telegram Delivery",
      deliveryFailed: "ផ្ញើមិនបានសម្រេច",
      systemHealth: "សុខភាពប្រព័ន្ធ",
      alerts: "alerts",
      recentUsers: "អ្នកប្រើប្រាស់ថ្មីៗ (Recent Users)",
      recentUsersSub: "គណនីដែលបានចុះឈ្មោះចុងក្រោយ",
      colName: "ឈ្មោះ",
      colEmail: "អ៊ីមែល",
      colRole: "តួនាទី",
      colStatus: "ស្ថានភាព",
      noUsersData: "មិនទាន់មានទិន្នន័យ",
      recentPayments: "ការទូទាត់ថ្មីៗ (Recent Payments)",
      recentPaymentsSub: "ប្រតិបត្តិការទូទាត់ចុងក្រោយក្នុងប្រព័ន្ធ",
      colOrderCode: "Order Code",
      colAmount: "ចំនួនទឹកប្រាក់",
      colDate: "កាលបរិច្ឆេទ",
      noPaymentsData: "មិនទាន់មានទិន្នន័យទូទាត់ទេ",
    },
    users: {
      title: "អ្នកប្រើប្រាស់",
      subtitle: "ស្វែងរក ពិនិត្យ បើកដំណើរការ ឬបិទគណនីអ្នកប្រើប្រាស់",
      detailSubtitle: "ព័ត៌មានលម្អិតអ្នកប្រើប្រាស់ និងបញ្ជីធៀបការ",
      searchPlaceholder: "ស្វែងរកអ្នកប្រើប្រាស់...",
      refresh: "ផ្ទុកឡើងវិញ",
      back: "ត្រឡប់ក្រោយ",
      colId: "ID",
      colName: "ឈ្មោះ",
      colEmail: "អ៊ីមែល / ទូរស័ព្ទ",
      colPhone: "លេខទូរស័ព្ទ",
      colRole: "តួនាទី",
      colStatus: "ស្ថានភាព",
      colJoined: "ថ្ងៃចូលរួម",
      colCreated: "កាលបរិច្ឆេទបង្កើត",
      colUpdated: "កាលបរិច្ឆេទកែប្រែ",
      colActions: "សកម្មភាព",
      activate: "បើកដំណើរការ",
      deactivate: "បិទដំណើរការ",
      invitationsTitle: "បញ្ជីធៀបការ",
      noInvitations: "មិនមានធៀបការទេ",
      toastSuccess: "បានធ្វើបច្ចុប្បន្នភាពអ្នកប្រើប្រាស់ជោគជ័យ",
      toastFail: "បរាជ័យក្នុងការធ្វើបច្ចុប្បន្នភាព",
    },
    invitations: {
      title: "ធៀបការ & RSVP",
      subtitle: "ពិនិត្យនិងគ្រប់គ្រងការផ្សាយធៀបការរបស់អ្នកប្រើប្រាស់ទាំងអស់",
      detailSubtitle: "ព័ត៌មានលម្អិតធៀបការ ស្ថានភាពផ្សព្វផ្សាយ និងការគ្រប់គ្រង Moderation",
      searchPlaceholder: "ស្វែងរកធៀបការ...",
      back: "ត្រឡប់ក្រោយ",
      filterAll: "ស្ថានភាពទាំងអស់",
      filterPublished: "ផ្សាយផ្ទាល់",
      filterDraft: "ព្រាង",
      filterActive: "ការត្រួតពិនិត្យសកម្ម",
      filterHidden: "លាក់",
      filterSuspended: "ផ្អាក",
      filterReported: "បានរាយការណ៍",
      colId: "ID",
      colTitle: "ចំណងជើង",
      colOwner: "ម្ចាស់ធៀប",
      colEvent: "ថ្ងៃកម្មវិធី",
      colStatus: "ស្ថានភាព",
      colModeration: "ការត្រួតពិនិត្យ",
      colSlug: "Slug",
      colTemplate: "គំរូធៀបការ",
      colVenue: "ទីតាំង",
      colVisibility: "កម្រិតមើលឃើញ",
      colActions: "សកម្មភាព",
      activate: "បើក",
      hide: "លាក់",
      suspend: "ផ្អាក",
      toastSuccess: "បានកែប្រែស្ថានភាពធៀបការជោគជ័យ",
      toastFail: "ការកែប្រែបរាជ័យ",
      confirmModerate: "តើអ្នកចង់កំណត់ស្ថានភាព Moderation ទៅជា {status} ឬទេ?",
    },
    payments: {
      title: "ការទូទាត់ (KHQR)",
      subtitle: "បញ្ជាទិញគំរូនិងកញ្ចប់សេវាកម្មពីប្រព័ន្ធទូទាត់សកម្ម",
      searchPlaceholder: "ស្វែងរកការទូទាត់...",
      statTotal: "សរុប",
      statPending: "រង់ចាំ",
      statPaid: "បានទូទាត់",
      statFailed: "បរាជ័យ",
      colOrder: "Order Code",
      colItem: "មុខទំនិញ / គំរូ",
      colType: "ប្រភេទ",
      colAmount: "ចំនួនទឹកប្រាក់",
      colMethod: "មធ្យោបាយ",
      colStatus: "ស្ថានភាព",
      colDate: "កាលបរិច្ឆេទ",
      colActions: "សកម្មភាព",
      confirmBtn: "បញ្ជាក់ការទូទាត់",
      confirmPrompt: "តើអ្នកពិតជាចង់ Confirm Payment សម្រាប់ Order {code} មែនទេ?",
      confirmSuccess: "Order {code} បាន Confirm ជោគជ័យ!",
    },
    packages: {
      title: "កញ្ចប់សេវាកម្ម",
      subtitle: "គ្រប់គ្រងតម្លៃនិងមុខងារនៃកញ្ចប់សេវាកម្មនីមួយៗ",
      searchPlaceholder: "ស្វែងរកកញ្ចប់...",
      createBtn: "+ បង្កើតកញ្ចប់ថ្មី",
      colName: "ឈ្មោះកញ្ចប់",
      colCode: "កូដ",
      colPrice: "តម្លៃ",
      colStatus: "ស្ថានភាព",
      colFeatures: "មុខងារ",
      colActions: "សកម្មភាព",
    },
    reports: {
      title: "របាយការណ៍ & Analytics",
      subtitle: "របាយការណ៍សង្ខេបអ្នកប្រើប្រាស់ ធៀបការ ការទូទាត់ RSVP និងប្រព័ន្ធ",
      tabUsers: "អ្នកប្រើប្រាស់",
      tabInvitations: "ធៀបការ",
      tabPayments: "ការទូទាត់",
      tabRsvp: "RSVP",
      tabSystem: "ប្រព័ន្ធ",
      noData: "មិនមានទិន្នន័យសម្រាប់របាយការណ៍នេះទេ",
    },
    notifications: {
      title: "ការជូនដំណឹង",
      subtitle: "ផ្ញើសារជូនដំណឹងប្រព័ន្ធទៅកាន់អ្នកប្រើប្រាស់ និងតាមដានស្ថានភាព",
      createTitle: "បង្កើតសារជូនដំណឹងប្រព័ន្ធ",
      userIdLabel: "User ID (ទុកទទេដើម្បីផ្ញើទាំងអស់)",
      userIdPlaceholder: "ឧ. 101 ឬទុកទទេ",
      typeLabel: "ប្រភេទ",
      channelLabel: "ប៉ុស្តិ៍ / Channel",
      titleLabel: "ចំណងជើង",
      titlePlaceholder: "ចំណងជើងសារ...",
      messageLabel: "ខ្លឹមសារសារ",
      messagePlaceholder: "សរសេរខ្លឹមសារនៅទីនេះ...",
      actionUrlLabel: "តំណភ្ជាប់ (Action URL)",
      actionUrlPlaceholder: "/dashboard ឬ https://...",
      sendBtn: "ផ្ញើសារជូនដំណឹង",
      sending: "កំពុងផ្ញើ...",
      colRecipient: "អ្នកទទួល",
      colType: "ប្រភេទ",
      colChannel: "ប៉ុស្តិ៍",
      colTitle: "ចំណងជើង",
      colStatus: "ស្ថានភាព",
      colSentAt: "កាលបរិច្ឆេទ",
      toastSuccess: "បានបង្កើតនិងផ្ញើសារជូនដំណឹងជោគជ័យ",
      toastFail: "មិនអាចផ្ញើសារជូនដំណឹងបានទេ",
    },
    systemLogs: {
      title: "កំណត់ហេតុប្រព័ន្ធ",
      subtitle: "តាមដាន Audit logs, Activity logs និង Exception logs ក្នុងប្រព័ន្ធ",
      searchPlaceholder: "ស្វែងរក logs...",
      levelAll: "កម្រិតទាំងអស់",
      levelInfo: "INFO",
      levelWarn: "WARN",
      levelError: "ERROR",
      colTimestamp: "ពេលវេលា",
      colLevel: "កម្រិត",
      colService: "សេវាកម្ម / Service",
      colMessage: "សារ / Event Details",
    },
    events: {
      title: "ព្រឹត្តិការណ៍",
      subtitle: "បញ្ជីព្រឹត្តិការណ៍អាពាហ៍ពិពាហ៍ទាំងអស់ក្នុងប្រព័ន្ធ",
      searchPlaceholder: "ស្វែងរកព្រឹត្តិការណ៍...",
      colId: "ID",
      colTitle: "ឈ្មោះកម្មវិធី",
      colCouple: "គូស្វាមីភរិយា",
      colDate: "កាលបរិច្ឆេទ",
      colVenue: "ទីតាំង",
      colStatus: "ស្ថានភាព",
    },
    templateEditor: {
      back: "ត្រឡប់ទៅបញ្ជីគំរូ",
      save: "រក្សាទុក & ផ្សាយ",
      saving: "កំពុងរក្សាទុក...",
      userTab: "មើល User Tab",
      themeTab: "រចនាបទ",
      musicTab: "តន្ត្រី & សំឡេង",
      scheduleTab: "កម្មវិធី & រូប",
      venueTab: "ទីតាំង & QR",
      settingsTab: "ការកំណត់",
      liveSimulator: "Live Simulator",
      coverView: "ស្រោមសំបុត្រ (Cover)",
      fullView: "មាតិកាពេញ (Full)",
      colorsFonts: "ពណ៌ & ពុម្ពអក្សរ (Colors & Fonts)",
      coverHero: "ស្រោម & កាតរូបថត (Cover & Hero)",
      gateStyle: "ម៉ូដរចនាបើកសំបុត្រ (Gate Opening Style)",
      cardMotion: "ចលនាកាត & ការរំកិល (Card Motion & Layout)",
      mobileView: "Mobile (380px)",
      tabletView: "Tablet (680px)",
      desktopView: "Desktop",
    },
  },
  en: {
    brandName: "KOUPRENG Wedding",
    brandSub: "Admin Management Portal",
    nav: {
      overview: "Overview",
      dashboard: "Dashboard",
      management: "Management",
      users: "Users",
      catalog: "Catalog & Pricing",
      templates: "Templates",
      packages: "Packages",
      finance: "Finance & Reports",
      payments: "Payments (KHQR)",
      reports: "Reports & Analytics",
      system: "System & Security",
      notifications: "Notifications",
      systemLogs: "System Logs",
    },
    topMenu: {
      notifications: "Notifications",
      themeLight: "Switch to Light Mode",
      themeDark: "Switch to Dark Mode",
      language: "Language",
      superAdmin: "SUPER ADMIN",
      account: "Account",
      profile: "Profile",
      signOut: "Sign Out",
      allUsers: "All Users Directory",
      searchPlaceholder: "Search records (name, email, code)...",
    },
    pageTitles: {
      "/dashboard": "Dashboard Overview",
      "/users": "User Management",
      "/templates": "Template Catalog",
      "/packages": "Pricing & Packages",
      "/payments": "KHQR Payment Reports",
      "/notifications": "Notification Center",
      "/system-logs": "System Logs",
      "/reports": "Summary & Analytics",
      fallback: "Koupreng Admin Portal",
    },
    common: {
      search: "Search...",
      filter: "Filter",
      all: "All",
      active: "Active",
      inactive: "Inactive",
      published: "Published",
      draft: "Draft",
      create: "Create New",
      edit: "Edit",
      delete: "Delete",
      save: "Save Changes",
      cancel: "Cancel",
      loading: "Loading...",
      noData: "No data available",
      actions: "Actions",
      status: "Status",
      date: "Date",
      close: "Close",
      refresh: "Reload",
      retry: "Try Again",
      viewAll: "View All",
      collapseMenu: "Collapse Menu",
      expandMenu: "Expand Menu",
    },
    dashboard: {
      eyebrow: "System Overview",
      title: "Dashboard",
      subtitle: "General analytics, user activity, and system health",
      reload: "Reload",
      loading: "Loading dashboard data...",
      error: "Unable to load dashboard data",
      totalUsers: "Total Users",
      activeAccounts: "Active Accounts",
      totalTemplates: "Templates",
      premiumTemplates: "Premium",
      totalInvitations: "Total Invitations",
      publishedInvitations: "Published",
      totalGuests: "Total Guests",
      allGuestsNote: "Across all invitations",
      totalPayments: "Total Payments",
      failedPayments: "Failed",
      totalRevenue: "Total Revenue",
      normalOperation: "Operational",
      rsvpConversion: "RSVP Conversion",
      rsvpRateNote: "Response rate vs total guests",
      checkInRate: "Check-in Rate",
      checkedInGuests: "Guests Checked-in",
      telegramDelivery: "Telegram Delivery",
      deliveryFailed: "Delivery Failed",
      systemHealth: "System Health",
      alerts: "alerts",
      recentUsers: "Recent Users",
      recentUsersSub: "Latest registered accounts",
      colName: "Name",
      colEmail: "Email",
      colRole: "Role",
      colStatus: "Status",
      noUsersData: "No user data available",
      recentPayments: "Recent Payments",
      recentPaymentsSub: "Latest payment transactions in system",
      colOrderCode: "Order Code",
      colAmount: "Amount",
      colDate: "Date",
      noPaymentsData: "No payment records found",
    },
    users: {
      title: "Users",
      subtitle: "Search, inspect, activate, and deactivate users",
      detailSubtitle: "User detail and owned invitations",
      searchPlaceholder: "Search users...",
      refresh: "Refresh",
      back: "Back",
      colId: "ID",
      colName: "Name",
      colEmail: "Email / Phone",
      colPhone: "Phone",
      colRole: "Role",
      colStatus: "Status",
      colJoined: "Joined Date",
      colCreated: "Created Date",
      colUpdated: "Updated Date",
      colActions: "Actions",
      activate: "Activate",
      deactivate: "Deactivate",
      invitationsTitle: "Invitations",
      noInvitations: "No invitations found",
      toastSuccess: "User updated successfully",
      toastFail: "User update failed",
    },
    invitations: {
      title: "Invitations & RSVP",
      subtitle: "Inspect and moderate invitations across all users",
      detailSubtitle: "Invitation detail, publication state, and moderation controls",
      searchPlaceholder: "Search invitations...",
      back: "Back",
      filterAll: "All Statuses",
      filterPublished: "Published",
      filterDraft: "Draft",
      filterActive: "Active Moderation",
      filterHidden: "Hidden",
      filterSuspended: "Suspended",
      filterReported: "Reported",
      colId: "ID",
      colTitle: "Title",
      colOwner: "Owner",
      colEvent: "Event Date",
      colStatus: "Status",
      colModeration: "Moderation",
      colSlug: "Slug",
      colTemplate: "Template",
      colVenue: "Venue",
      colVisibility: "Visibility",
      colActions: "Actions",
      activate: "Activate",
      hide: "Hide",
      suspend: "Suspend",
      toastSuccess: "Invitation moderated successfully",
      toastFail: "Moderation failed",
      confirmModerate: "Set moderation status to {status}?",
    },
    payments: {
      title: "Payments (KHQR)",
      subtitle: "Template and subscription payment orders from active API",
      searchPlaceholder: "Search payments...",
      statTotal: "Total",
      statPending: "Pending",
      statPaid: "Paid",
      statFailed: "Failed",
      colOrder: "Order Code",
      colItem: "Item / Template",
      colType: "Type",
      colAmount: "Amount",
      colMethod: "Method",
      colStatus: "Status",
      colDate: "Date",
      colActions: "Actions",
      confirmBtn: "Confirm Payment",
      confirmPrompt: "Are you sure you want to confirm payment for Order {code}?",
      confirmSuccess: "Order {code} confirmed successfully!",
    },
    packages: {
      title: "Pricing & Packages",
      subtitle: "Manage package tiers, features, and pricing",
      searchPlaceholder: "Search packages...",
      createBtn: "+ Create Package",
      colName: "Package Name",
      colCode: "Code",
      colPrice: "Price",
      colStatus: "Status",
      colFeatures: "Features",
      colActions: "Actions",
    },
    reports: {
      title: "Reports & Analytics",
      subtitle: "Comprehensive reports for users, invitations, payments, and RSVP",
      tabUsers: "Users",
      tabInvitations: "Invitations",
      tabPayments: "Payments",
      tabRsvp: "RSVP",
      tabSystem: "System",
      noData: "No row data for this report.",
    },
    notifications: {
      title: "Notifications",
      subtitle: "Send system notifications to users and view delivery statuses",
      createTitle: "Create System Notification",
      userIdLabel: "User ID (Leave empty for broadcast)",
      userIdPlaceholder: "e.g. 101 or empty for all",
      typeLabel: "Type",
      channelLabel: "Channel",
      titleLabel: "Title",
      titlePlaceholder: "Notification title...",
      messageLabel: "Message Content",
      messagePlaceholder: "Write notification message here...",
      actionUrlLabel: "Action URL",
      actionUrlPlaceholder: "/dashboard or https://...",
      sendBtn: "Send Notification",
      sending: "Sending...",
      colRecipient: "Recipient",
      colType: "Type",
      colChannel: "Channel",
      colTitle: "Title",
      colStatus: "Status",
      colSentAt: "Sent At",
      toastSuccess: "Notification created and sent successfully",
      toastFail: "Could not send notification",
    },
    systemLogs: {
      title: "System Logs",
      subtitle: "Monitor audit logs, activity events, and exceptions across services",
      searchPlaceholder: "Search logs...",
      levelAll: "All Levels",
      levelInfo: "INFO",
      levelWarn: "WARN",
      levelError: "ERROR",
      colTimestamp: "Timestamp",
      colLevel: "Level",
      colService: "Service",
      colMessage: "Event Details",
    },
    events: {
      title: "Events",
      subtitle: "All wedding events registered in the system",
      searchPlaceholder: "Search events...",
      colId: "ID",
      colTitle: "Event Name",
      colCouple: "Couple",
      colDate: "Event Date",
      colVenue: "Venue",
      colStatus: "Status",
    },
    templateEditor: {
      back: "Back to Templates",
      save: "Save & Publish",
      saving: "Saving...",
      userTab: "Open User Tab",
      themeTab: "Theme & Styles",
      musicTab: "Music & Audio",
      scheduleTab: "Schedule & Photos",
      venueTab: "Venue & QR",
      settingsTab: "Settings",
      liveSimulator: "Live Simulator",
      coverView: "Envelope (Cover)",
      fullView: "Full Invitation (Full)",
      colorsFonts: "Colors & Fonts",
      coverHero: "Cover & Hero Photo",
      gateStyle: "Gate Opening Style",
      cardMotion: "Card Motion & Layout",
      mobileView: "Mobile (380px)",
      tabletView: "Tablet (680px)",
      desktopView: "Desktop",
    },
  },
};

const AdminLanguageContext = createContext({
  lang: "km",
  setLang: () => {},
  t: (path, fallback) => fallback || path,
  messages: ADMIN_DICTIONARY.km,
});

function formatTemplate(text, replacements) {
  if (!replacements || typeof text !== "string") return text;
  return Object.entries(replacements).reduce(
    (acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)),
    text
  );
}

export function AdminLanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY) || localStorage.getItem("koupreng.lang");
      return stored === "en" ? "en" : "km";
    } catch {
      return "km";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
      localStorage.setItem("koupreng.lang", lang);
    } catch {
      // ignore storage errors
    }
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = useCallback((nextLang) => {
    if (nextLang === "km" || nextLang === "en") {
      setLangState(nextLang);
    }
  }, []);

  const messages = useMemo(() => ADMIN_DICTIONARY[lang] || ADMIN_DICTIONARY.km, [lang]);

  const t = useCallback((path, fallback = "", replacements = null) => {
    if (!path) return fallback;
    const parts = path.split(".");
    let current = messages;
    for (const part of parts) {
      if (current && typeof current === "object" && part in current) {
        current = current[part];
      } else {
        const fallbackVal = fallback || path;
        return replacements ? formatTemplate(fallbackVal, replacements) : fallbackVal;
      }
    }
    const val = typeof current === "string" ? current : fallback || path;
    return replacements ? formatTemplate(val, replacements) : val;
  }, [messages]);

  const value = useMemo(() => ({ lang, setLang, t, messages }), [lang, messages, setLang, t]);

  return (
    <AdminLanguageContext.Provider value={value}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  return useContext(AdminLanguageContext);
}

export default AdminLanguageProvider;
